"""add updated_by to tenders

Revision ID: 023e8e649151
Revises: fe28531ffeb6
Create Date: 2026-08-23 18:16:20.774717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023e8e649151'
down_revision: Union[str, Sequence[str], None] = 'fe28531ffeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('tenders', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.execute('UPDATE tenders SET updated_by = created_by WHERE updated_by IS NULL')
    op.alter_column('tenders', 'updated_by', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'updated_by')
    # ### end Alembic commands ###
