"""make update_reason required

Revision ID: a716200b052e
Revises: 023e8e649151
Create Date: 2026-08-23 18:26:33.643265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a716200b052e'
down_revision: Union[str, Sequence[str], None] = '023e8e649151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "UPDATE tender_status_change_log SET update_reason = 'Reason not recorded (legacy record)' "
        "WHERE update_reason IS NULL"
    )
    op.alter_column('tender_status_change_log', 'update_reason',
               existing_type=sa.TEXT(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tender_status_change_log', 'update_reason',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
