"""create tendes tables

Revision ID: fe28531ffeb6
Revises: 
Create Date: 2026-08-23 13:33:50.090996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe28531ffeb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'WON', 'LOST', name='tender_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issuer_name', sa.String(length=255), nullable=False),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenders_created_by', 'tenders', ['created_by', 'created_at'], unique=False)
    op.create_index('ix_tenders_updated_at', 'tenders', ['updated_at'], unique=False)
    op.create_table('tender_status_change_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('DRAFT', 'ACTIVE', 'WON', 'LOST', name='tender_status'), nullable=False),
    sa.Column('new_status', sa.Enum('DRAFT', 'ACTIVE', 'WON', 'LOST', name='tender_status'), nullable=False),
    sa.Column('update_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tender_status_changed_by', 'tender_status_change_log', ['changed_by', 'changed_at'], unique=False)
    op.create_index('ix_tender_status_tender_changed', 'tender_status_change_log', ['tender_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tender_status_tender_changed', table_name='tender_status_change_log')
    op.drop_index('ix_tender_status_changed_by', table_name='tender_status_change_log')
    op.drop_table('tender_status_change_log')
    op.drop_index('ix_tenders_updated_at', table_name='tenders')
    op.drop_index('ix_tenders_created_by', table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
